# Generated by Django 4.1.3 on 2022-11-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='system_user',
        ),
    ]
